development:
  adapter: postgresql
  encoding: unicode
  database: react_rails_browserify_development
  pool: 5

test:
  adapter: postgresql
  encoding: unicode
  database: react_rails_browserify_test
  pool: 5
